### ISSUE TITLE
Change temperature using API

### ISSUE THREAD

**Issue by christian-ek** [hellange/lksystems#1]
Hi,
Do you know if it's possible to change temperature using lk webserver API? 
Do you have any documentation for the API? Can't find any information at all except for this repo.

**Comment by hellange** [comment]
Hi, it's been a while since I wrote this code (and tested that it works !). But If I remember correctly, I reverse engineered the protocol based on the network traffic I found using the web interface.  Should be possible to do the same for changing temperature I believe. But I also know that they have upgraded the webserver (I'm still running the old) since then (swedish: https://www.lksystems.no/globalassets/lk-systems/documents/lk-webserver/lk-webserver_instruktion-for-uppdatering.pdf). If I were you, I would contact them directly.

**Comment by christian-ek** [comment]
I reverse engineered it like you said directly after posting this and got it working. Thank you for the input!
